name: talehive
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  fl_chart: ^0.66.2
  http: ^1.1.0
  intl: ^0.18.1
  file_picker: ^8.0.0+1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  firebase_database: ^12.0.0
  cloud_firestore: ^6.0.0
  google_sign_in: ^6.1.5
  syncfusion_flutter_pdfviewer: ^30.1.42
  url_launcher: ^6.3.2
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  path_provider: ^2.1.4
  path: ^1.8.3
  image_picker: ^1.0.4
  firebase_storage: ^13.0.0
  image: ^4.1.3 # For image compression
firebase_storage: ^13.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: Asset/images/
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "Asset/images/icon.jpg"




flutter:




  uses-material-design: true
  assets:
    - Asset/images/






























